server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service.product-service:8082
          predicates:
            - Path=/products/**

        - id: order-service
          uri: http://order-service.order-service:8083
          predicates:
            - Path=/orders/**
            
        - id: user-service
          uri: http://user-service.user-service:8081
          predicates:
            - Path=/users/**,/login,/refresh,/logout
        
