namespace: api-gateway
replicaCount: 2


deployment:
  name: api-gateway-deployment

service:
  name: api-gateway
  port: 8000
  type: ClusterIP
  targetPort: 8000

image:
  repository: jeongmin0709/api-gateway
  tag: "1.0.3"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: api-gateway-sa

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  className: nginx
  path: /api(/|$)(.*)
  pathType: ImplementationSpecific

configMap:
  name: api-gateway-cm

secret:
  name: api-gateway-secret

env:
  - name: SPRING_CONFIG_LOCATION
    value: "file:/app/config/application.yaml"
  - name: PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        name: api-gateway-secret
        key: public-key
volumeMounts:
  - name: config-volume
    mountPath: /app/config/application.yaml
    subPath: application.yaml