namespace: api-gateway
replicaCount: 2


deployment:
  name: api-gateway-deployment

service:
  name: api-gateway
  port: 8000
  type: ClusterIP
  targetPort: 8000

image:
  repository: jeongmin0709/msa_repository
  tag: "api-gateway-latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: api-gateway-sa

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
  className: nginx
  path: /api
  pathType: Prefix