namespace: api-gateway
replicaCount: 2


deployment:
  name: api-gateway-deployment

service:
  name: api-gateway
  port: 8000
  type: ClusterIP
  targetPort: 8000

image:
  repository: jeongmin0709/msa_repository
  tag: "api-gateway"
  version: "53"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: api-gateway-sa

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  className: nginx
  path: /api(/|$)(.*)
  pathType: ImplementationSpecific

configMap:
  name: api-gateway-cm

env:
  - name: SPRING_CONFIG_LOCATION
    value: "file:/app/config/application.yaml"

volumeMounts:
  - name: config-volume
    mountPath: /app/config/application.yaml
    subPath: application.yaml