apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name  }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name  }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name  }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Chart.Name  }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s