name: product-service
namespace: product-service
replicaCount: 1

service:
  name: product-service
  port: 8003
  type: ClusterIP
  targetPort: 8003

image:
  repository: jeongmin0709/product-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: product-service-sa
configMap:
  name: product-service-cm
env:
  - name: SPRING_CONFIG_LOCATION
    value: "file:/app/config/application.yaml"
volumeMounts:
  - name: config-volume
    mountPath: /app/config/application.yaml
    subPath: application.yaml

resources:
  requests:
    cpu: 350m
    memory: 300Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
