name: product-service
namespace: product-service
replicaCount: 2


deployment:
  name: product-service-deployment

service:
  name: product-service
  port: 8003
  type: ClusterIP
  targetPort: 8003

image:
  repository: jeongmin0709/msa_repository
  tag: "product-service"
  version: "51"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: product-service-sa

configMap:
  name: product-service-cm

secret:
  name: product-service-secret

env:
  - name: SPRING_CONFIG_LOCATION
    value: "file:/app/config/application.yaml"

volumeMounts:
  - name: config-volume
    mountPath: /app/config/application.yaml
    subPath: application.yaml

