name: order-service
namespace: order-service
replicaCount: 2

service:
  name: order-service
  port: 8002
  type: ClusterIP
  targetPort: 8002

image:
  repository: jeongmin0709/order-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: order-service-sa

configMap:
  name: order-service-cm


env:
  - name: SPRING_CONFIG_LOCATION
    value: "file:/app/config/application.yaml"

volumeMounts:
  - name: config-volume
    mountPath: /app/config/application.yaml
    subPath: application.yaml

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

