name: order-service
namespace: order-service
replicaCount: 2

service:
  name: order-service
  port: 8002
  type: ClusterIP
  targetPort: 8002

image:
  repository: jeongmin0709/order-service
  tag: "1.0.2"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: order-service-sa

configMap:
  name: order-service-cm


env:
  - name: SPRING_CONFIG_LOCATION
    value: "file:/app/config/application.yaml"

volumeMounts:
  - name: config-volume
    mountPath: /app/config/application.yaml
    subPath: application.yaml

