apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name  }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name  }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name  }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Chart.Name  }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "file:/app/config/application.yaml"
        - name: KEY_PATH
          value: "file:/app/secret/private_key_pkcs8.pem"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config/application.yaml
          subPath: application.yaml
        - name: secret-volume
          mountPath: /app/secret/private_key_pkcs8.pem
          subPath: private_key_pkcs8.pem
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.configMap.name }}
          namespace: {{ .Values.namespace }}
      - name: secret-volume    
        secret:
          secretName: {{ .Values.secret.name }}
          namespace: {{ .Values.namespace }}