server:
  port: 8001

spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  data:
    redis:
      host: redis-master.redis.svc.cluster.local
      port: 6379
      password: ${REDIS_PASSWORD}
    
  application:
    name: user-service

management:
  tracing:
    sampling:
      probability: 1.0  # 모든 요청 추적
  zipkin:
    tracing:
      endpoint: http://my-zipkin-collector.zipkin.svc.cluster.local/api/v2/spans

  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  expire-time:
    access-token: 900000
    refresh-token: 2592000000