name: user-service
namespace: user-service
replicaCount: 1

service:
  name: user-service
  port: 8001
  type: ClusterIP
  targetPort: 8001

image:
  repository: jeongmin0709/user-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: user-service-sa

configMap:
  name: user-service-cm

secret:
  name: user-service-secret

env:
  - name: SPRING_CONFIG_LOCATION
    value: "file:/app/config/application.yaml"
  - name: PRIVATE_KEY
    valueFrom:
      secretKeyRef:
        name: user-service-secret
        key: private-key

volumeMounts:
  - name: config-volume
    mountPath: /app/config/application.yaml
    subPath: application.yaml

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

