name: user-service
namespace: user-service
replicaCount: 2

service:
  name: user-service
  port: 8001
  type: ClusterIP
  targetPort: 8001

image:
  repository: jeongmin0709/user-service
  tag: "1.0.62"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: user-service-sa

configMap:
  name: user-service-cm

secret:
  name: user-service-secret

env:
  - name: SPRING_CONFIG_LOCATION
    value: "file:/app/config/application.yaml"
  - name: PREVATE_KEY
    valueFrom:
      secretKeyRef:
        name: user-service-secret
        key: prevate-key
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis
        key: redis-password

volumeMounts:
  - name: config-volume
    mountPath: /app/config/application.yaml
    subPath: application.yaml

