name: helm push

on:
  repository_dispatch:
    types: HELM-PUSH

env:
  SERVICE: ${{ github.event.client_payload.service }}
  TAG: ${{ github.event.client_payload.tag }}
jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      # 1. repo 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Tag
        run: |
          sudo apt-get update && sudo apt-get install -y yq
          yq e -i -y ".image.tag = \"$TAG\"" ./$SERVICE/values.yaml

      # 3. git 설정
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      # 4. Commit
      - name: Commit changes
        run: |
          git add ./$SERVICE
          git commit -m "Update version to 1.0.$TAG" 

      # 5. Push 
      - name: Push changes
        run: git push origin main
